sudo: required

language: generic

services:
  - docker

before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -f Dockerfile -t nodered/node-red-docker .


script:
  - docker run -d nodered/node-red-docker:latest
  - docker ps | grep latest

